{
 "title": "Text Embedding Inference",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(te_request_count, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(te_request_success{container=\"$service\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(te_request_failure{container=\"$service\"}[1m])) by (err)",
     "legendFormat": "Error: {{err}}"
    }
   ]
  },
  {
   "title": "Number of tokens per prompt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_input_length_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_input_length_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_input_length_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Batching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Queue quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_queue_duration_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_queue_duration_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_queue_duration_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_input_length_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_input_length_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_input_length_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_duration_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_duration_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_duration_bucket{container=\"$service\"}[10m])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}