name: lint-dockerfiles

on:
  push:
    branches:
    - master
  pull_request:
    paths:
    - '**/Dockerfile'
    - '**/docker-compose.yaml'

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint Docker Compose files
      run: |
        compose_files=$(find . -name "docker-compose.yaml")
        for file in $compose_files; do
          echo "Linting $file"
          docker compose -f $file config -q --no-interpolate || exit 1
        done
    - name: Lint Dockerfiles
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: "*Dockerfile"
        ignore: "DL3006,DL3008,DL3013"
        recursive: 'true'
